### ISSUE TITLE
Uncaught error. Trying to upload a file with different encoding

### ISSUE THREAD

**Issue by dciccale** [hapijs/faketoe#33]
```
Debug: internal, implementation, error 
    Error: Uncaught error: Uncaught, unspecified "error" event.
    at Error (native)
    at emit (events.js:87:13)
    at onerror (_stream_readable.js:556:12)
    at emit (events.js:107:17)
    at Parser.write (/Users/Denis/git/asd/node_modules/faketoe/node_modules/node-expat/lib/node-expat.js:68:10)
    at ondata (_stream_readable.js:540:20)
    at emit (events.js:107:17)
    at Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickDomainCallback (node.js:381:11)
```

I'm am trying to upload a file which the encoding is `latin1`

However, I am setting the encoding to utf8 but still fails

```js
server.route({
  config: {
    payload: {
      parse: true,
      output: 'stream'
    }
  },
  method: 'POST',
  path: '/',
  handler: function (request, reply) {
    var file = req.payload.file

    var parser = Faketoe.createParser(function (err, result) {
      if (!err) {
        reply(result);
      }
    });

    file.setEncoding('utf8');
    file.pipe(parser);
  }
});
```

if i manually change the xml file encoding with vim `: set fenc=utf8` and then upload again, it works

**Comment by dciccale** [comment]
I found a solution using [iconv-lite](https://www.npmjs.com/package/iconv-lite)

```js
    file
      .pipe(iconv.decodeStream('latin1'))
      .pipe(iconv.encodeStream('utf8'))
      .pipe(parser);
```

**Comment by nlf** [comment]
supporting different encodings isn't a bad idea. this module needs some refreshing anyway, so i'll check it out
